name: Update SDK
on:
  schedule:
    - cron: '0 0 * * *'
  ## Manual request that can be used for testing and retriggering failed updates
  workflow_dispatch:
jobs:
  generate_client:
    env:
      APP_SERVICES_TOKEN: ${{ secrets.APP_SERVICES_TOKEN }}
      BF2_TOKEN: ${{ secrets.BF2_TOKEN }}

    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v3
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10' 
      - name: Install jq
        run: sudo apt-get install jq
      - name: Fetch OpenAPI doc
        run: python scripts/fetch_api.py
      - name: Make pull request
        uses: peter-evans/create-pull-request@v4
        with:
            title: "fix(${{ github.event.client_payload.id }}): automated openapi files update"
            commit-message: "fix(${{ github.event.client_payload.id }}): update for ${{ github.event.client_payload.id }} SDK"
            author: "app-services-ci <app-services-ci@users.noreply.github.com>"
            branch: chore/generate-api-clients
            branch-suffix: timestamp
            delete-branch: true
            body: |
              _This pull request was auto-generated_

              This PR adds the latest openapi files
